### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by kevinbowman-aiven** [aiven/aiven-db-migrate#31]
### Description of the issue
The tool doesn't work on a Mac, because of the hard-coded list of directories where the postgres tooling is available.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement
- [ ] Other

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS - MacOS Monterey 12.1
* Python Version - 3.9.10
* Release tag/commit of the code - tag: 0.0.5 / commit 57427dec8609ab8c8ec57cb87682b4e8c003c8c9

### Expected behaviour
The tool should proceed as expected

### Actual behaviour
```
aiven_db_migrate.migrate.errors.PGMigrateValidationFailedError: Couldn't find bin dir for any pg version between '14.0' and '14.2', tried ['/usr/pgsql-([0-9]+(\\.[0-9]+)*)/bin', '/usr/lib/postgresql/([0-9]+(\\.[0-9]+)*)/bin']
```

### Steps to reproduce
Run any aiven-db-migrate command on a Mac

### Any extra info ( for eg. code snippet to reproduce, logs, screenshots etc. )
The tool does work if this check is overridden.  I have psql installed through Homebrew, so the binaries are available in `/opt/homebrew/bin`.  Line 29 in `pgutils.py` is trying to get the version number from the path, which isn't available in the homebrew method, but if I change line 1180 in `pgmigrate.py` to:
```
self.pgbin = Path("/opt/homebrew/bin")
```
then the tool proceeds to work as expected.  This isn't the right solution, it's only so I could check that there aren't any other problems, but it suggests that it's worth solving the issue properly.

**Comment by runwuf** [comment]
@kevinbowman-aiven 
I have created this [PR](https://github.com/aiven/aiven-db-migrate/pull/35) which allows pg installed on Mac that is not in /usr/ to work, in my case it would be running the command such as:
`PGHOMEDIR=/Applications/Postgres.app/Contents/Versions/ python3 aiven_db_migrate/migrate/pgmigrate.py . . .`
It doesn't address your case with homebrew install as it checks directory naming for support pg version...
@alanfranz-at-work feedback on ideas?

**Comment by runwuf** [comment]
@kevinbowman-aiven 
this is fixed by adding `--pgin` flag
code has been merged https://github.com/aiven/aiven-db-migrate/pull/35

**Comment by kevinbowman-aiven** [comment]
Fantastic, thanks!
