### ISSUE TITLE
Preferred users/target dbs?

### ISSUE THREAD

**Issue by thedevelopnik** [aiven/aiven-db-migrate#5]
We're about to use this to test logical replication migration from databases we fully own in our infrastructure to Aiven databases.

Two main questions:
Is a superuser ok to use on the source db?
For the target database, if we want to not use the `defaultdb` but a different db that is app specific, are there any permissions we should set up for the avnadmin user before running the migration tool?

Thanks!

**Comment by rikonen** [comment]
Superuser should be fine. avnadmin should by default have the same permissions to all databases.

**Comment by thedevelopnik** [comment]
Great thanks!
