### ISSUE TITLE
Tool does not work with socket connections

### ISSUE THREAD

**Issue by nickgsc** [aiven/aiven-db-migrate#6]
In our environment, our source database superuser connection is limited only to socket connections, and not standard TCP/network connections. According to the docs, any valid libpq connection string should work, but it fails if you pass in a connection string with no host/port defined.

```
Traceback (most recent call last):
  File "/var/lib/postgresql/aiven-db-migrate/aiven_db_migrate/migrate/pgmigrate.py", line 943, in validate
    self.source.conn_info["host"] == self.target.conn_info["host"]
KeyError: 'host'
```

The connection string in question works with psql:
```
postgres@linus-db:~/aiven-db-migrate$ psql "postgres:///dafhp6nhpahgqn"
psql (12.1 (Ubuntu 12.1-1.pgdg18.04+1))
Type "help" for help.

dafhp6nhpahgqn=# \conninfo
You are connected to database "dafhp6nhpahgqn" as user "postgres" via socket in "/var/run/postgresql" at port "5432".
dafhp6nhpahgqn=#
```

**Comment by nickgsc** [comment]
It would be fine for us to grant the extra permissions needed to a non-superuser role that has network connectivity (and honestly it's less messy than running this code directly on the source db), but the docs are unclear as to exactly what permissions would be needed to support this.

**Comment by gabriel-tincu** [comment]
did you try to add the unix socket file as the `host` parameter?

**Comment by nickgsc** [comment]
Ok, it seems to get past the parsing step at least if I do the connection string in this format:
`"postgres:///dafhp6nhpahgqn?host=/var/run/postgresql"`

Running into a different problem now with the binary detection

**Comment by gabriel-tincu** [comment]
I think I'll need a better understanding of your use case . Are you trying to replicate from one cluster to the other, both running on the same machine ?

**Comment by nickgsc** [comment]
We were attempting to replicate from an instance that does not expose a superuser account with login rights, but it seems that fundamentally won't work because of the way the replication has to connect. We set up a secondary superuser with login rights specifically for running this replication/migration in order to proceed. Closing this issue out.
